=== tbogajce/Poslovna-informatika/public/xmlovi/sema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/nalog" xmlns:nal="http://www.ftn.uns.ac.rs/nalog">

    <xs:element name="nalozi">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="nalog_za_prenos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="podaci_o_duzniku" type="nal:TFizicko_lice"/>
                            <xs:element name="podaci_o_poveriocu" type="nal:TPravno_lice"/>
                            <xs:element name="svrha_placanja" type="xs:string"/>
                            <xs:element name="podaci_o_uplati">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sifra_placanja"/>
                                        <xs:element name="valuta"/>
                                        <xs:element name="iznos"/>
                                        <xs:element name="racun_primaoca"/>
                                        <xs:element name="transfer_podaci">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="broj_modela"/>
                                                  <xs:element name="poziv_na_broj"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice"/>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="nal:TLice">
                <xs:sequence>
                    <xs:element name="naziv" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="nal:TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                    <xs:element name="adresa" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== tbogajce/Poslovna-informatika/public/xmlovi/primjerXml.xml
<?xml version="1.0" encoding="UTF-8"?>
<nalozi xmlns="http://www.ftn.uns.ac.rs/nalog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/nalog file:/C:/Users/skilj/Desktop/sema.xsd">
    <nalog_za_prenos>
        <podaci_o_duzniku>
            <ime>Milivoje</ime>
            <prezime>Skiljevic</prezime>
            <adresa>Knez Mihajlova</adresa>
        </podaci_o_duzniku>
        <podaci_o_poveriocu>
            <naziv>FTN</naziv>
        </podaci_o_poveriocu>
        <svrha_placanja>Prijava ispita</svrha_placanja>
        <podaci_o_uplati>
            <sifra_placanja>189</sifra_placanja>
            <valuta>RSD</valuta>
            <iznos>2000.00</iznos>
            <racun_primaoca>840-7771144-183</racun_primaoca>
            <transfer_podaci>
                <broj_modela>97</broj_modela>
                <poziv_na_broj>12-12212-1-1444-12183</poziv_na_broj>
            </transfer_podaci>
        </podaci_o_uplati>
    </nalog_za_prenos>
    <nalog_za_prenos>
        <podaci_o_duzniku>
            <ime>dasd</ime>
            <prezime>dasd</prezime>
            <adresa>dasd</adresa>
        </podaci_o_duzniku>
        <podaci_o_poveriocu>
            <naziv>dasd</naziv>
        </podaci_o_poveriocu>
        <svrha_placanja>dasdasd</svrha_placanja>
        <podaci_o_uplati>
            <sifra_placanja>88</sifra_placanja>
            <valuta>rsd</valuta>
            <iznos>154</iznos>
            <racun_primaoca>dasd-asdsd</racun_primaoca>
            <transfer_podaci>
                <broj_modela>97</broj_modela>
                <poziv_na_broj>12212-1221212-1212</poziv_na_broj>
            </transfer_podaci>
        </podaci_o_uplati>
    </nalog_za_prenos>
</nalozi>
